### ISSUE TITLE
ToString Method is not implemented, making it harder to debug

### ISSUE THREAD

**Issue by oalpar** [StinkySteak/netick-ticktimer#3]
![image](https://github.com/user-attachments/assets/1861290c-52fa-4a53-9e78-d2de6a9bcd57)
![image](https://github.com/user-attachments/assets/64caff73-7400-426b-9966-9534194103b1)
Neticks default timer logs the target tick, hoping same behaviour can be achieved in steak timer, thanks!

**Comment by StinkySteak** [comment]
Added, now available for all tickTimers
